-- 1 > 9: growth zone
--     P: Player
--     A: Portal
--     M: Moving
--     #: Brick - jump prevented
--     G: Brick - jump allowed
--     H: Brick - visible but path allowed
return [[
                                                                                                                                                                                          ################################################################################################################
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                                                                       E                                      #
                                                                                                                                                                                          #                                                                     GGGGG                                    #
                                                                                                                                                                                          #                                                      GGG                                                     #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                                              NNN                                                             #
                                                                                                                                                                                          #                                                                                       GGGG                   #
                                                                                                                                                                                          #                      GGGG                    GGGG                                                            #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                                   GGGG                                                                       #
                                                                                                                                                                                          #      GGG                                                         GGGGG                                       #
                                                                                                                                                                                          #                                                      MMM                                                     #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                                        GGGG                                                                  #
                                                                                                                                                                                          #                    GGGGG                                                           GGGG                      #
                                                                                                                                                                                          #                                                                     D                                        #
                                                                                                                                                                                          #                                                                  GGGGGG                                      #
                                                                                                                                                                                          #                                                  GGGG                 #                                      #
                                                                                                                                                                                          #           GGGGG                                                       #         E                            #
                                                                                                                                                                                          #                                                                       #       GGGG                           #
                                                                                                                                                                                          #                                                                       #                                      #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #            GGG                         GGG                C     D                                            #
                                                                                                                                                                                          #                                                  GGG     GGGGGGGGG                  GGG               GGG    #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #       GGGG                                                    GGG                                            #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                    GGGG                   GGG                     GGGG                                       #
                                                                                                                                                                                          #                                                                                      GGG                     #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                                                                                               GGGG           #
                                                                                                                                                                                          #                          GGG                                   GGG         GGGG                              #
                                                                                                                                                                                          #                                    GGGG            B                                   GGGG                  #
                                                                                                                                                                                          #                                                    GGGG                                                      #
                                                                                                                                                                                          #                 NNNNNN                                                                                       #
                                                                                                                                                                                          #                                                                                                              #
                                                                                                                                                                                          #                                      NNNNNN                     C                      GGGG      GGGGG       #
                                                                                                                                                                                          #                                                               MMMMM                                          #
###########################################################################################################################################################################################                                                                                GGGGGG                        #
#                                                             #A                                                                                                                          #                                      GGG                                                                     #
#                                                             #GGGG                                                                                                                       #                             NNNNNN                              NNNN                    GGGGGGG              #
#                                                                                     GGGGGGG                          G                               GGG                                #                                                                                                              #
#                                                                                  GGG#######                         G#                          GG     #                                #             MM                                                                                       GGGGGGGG#
#                                                                               GGG##########                      G   #                         G       #                                                                                          MMMMM                       GGGG    GGGGGG           #
#                                                                            GGG#############                   G      #                       GGG       #                                      GG                                         NNNNN                                                         #
#                                                   3                     GGGG###############                G         #                   N             #                                                          NNNN                                 MMMMMMM                     GG        GG        #
#                                                  GGG                 GGGG##################         GGG              #                    M            #                                #                MMMMM                                                    GG    GG             GG              #
#  2                            P                 G###G              GGG#####################              G           #                 N               #               6                #                                                                                   GG            GG          B#
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGHGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGHHGGGGGGGGGGGGGGGGGGGGGGGHGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGHHGG
                                                      # #####                               #G                         #
                                                      #     #                               #GGG   5                   #
#######################################################     #                               #GGGGGGGGGGGGGGGGGGGGGGGGGG#
#                                                     #     #
#                                                     #GGG  #
#A                                             4            #
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG#
]]
